name = "GraphDigitizer"
uuid = "b7c2e045-0d85-4a3b-b2a1-9f1a59c82db1"
authors = ["Michael Ryan Hunsaker, M.Ed., Ph.D. <ryhunsaker@dsdmail.net>"]
version = "1.2.0-beta"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Graphics = "a2bd30eb-e257-5431-a919-1863eab51364"
Gtk = "4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"


[compat]
CSV = "0.10.15"
Cairo = "1.1.1"
ColorTypes = "0.12.1"
Colors = "0.13.1"
DataFrames = "1.8.0"
FileIO = "1.17.0"
GeometryBasics = "0.5.10"
Gtk = "1.3.1"
ImageCore = "0.10.5"
ImageIO = "0.6.9"
ImageMagick = "1.4.2"
JSON = "0.21.4"

